# SPA: h2_only（子域 h2_only.<this_should_be_replaced_by_root_domain>，stream 已按 SNI 转到 9443）
server {
    listen 127.0.0.1:9443 ssl proxy_protocol reuseport;

    http2 on;

    root /usr/share/nginx/html;
    index h2_only.html;

    server_name h2_only.<this_should_be_replaced_by_root_domain>;

    if ($server_protocol != "HTTP/2.0") {
        return 426;
    }
}
